name: Update release from zip

on:
  schedule:
    # Run every day at 00:00 UTC, which is 08:00 Beijing time
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      
      - name: Download zip file from https://zip.baipiao.eu.org/
        run: |
          curl -H "User-Agent: Mozilla/5.0" -H "Accept-Encoding: gzip" -o txt.zip https://zip.baipiao.eu.org/  # Specify the output file name as txt.zip
      
      - name: Delete old release branch
        run: |
          git push origin --delete release || true # Ignore errors if branch does not exist
      
      - name: Create new release branch
        run: |
          git checkout --orphan release # Create a new branch with no history
          git rm -rf . # Remove all files from the working directory
          git clean -fxd # Remove all untracked files from the working directory
      
      - name: Copy txt.zip file to release branch
        run: |
          cp txt.zip . # Copy txt.zip file to current directory
          git add . # Add all files to staging area
          git commit -m "Update release from txt.zip file" # Commit changes
      
      - name: Push release branch to remote
        run: |
          git push origin release # Push release branch to remote repository
